export const CHAT_BUBBLE_PREFIX_LIST = [
  'chat',
  'chat-image',
  'chat-header',
  'chat-footer',
  'chat-bubble',
  'chat-start',
  'chat-end',
  'chat-bubble-neutral',
  'chat-bubble-primary',
  'chat-bubble-secondary',
  'chat-bubble-accent',
  'chat-bubble-info',
  'chat-bubble-success',
  'chat-bubble-warning',
  'chat-bubble-error',
];
